apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 71-worker-ssh-motd
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
      - contents:
          compression: ""
          source: data:text/plain;charset=utf-8;base64,IF9fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fXwp8ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgfAp8IFVOQVVUSE9SSVpFRCBBQ0NFU1MgVE8gVEhJUyBTWVNURU0gSVMgUFJPSElCSVRFRC4gICAgICAgICAgICAgICAgICAgICAgICAgfAp8ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgfAp8IElGIFlPVSBBUkUgTE9PS0lORyBGT1IgUkFOU09NLCBJIENBTiBURUxMIFlPVSBJIERPTidUIEhBVkUgTU9ORVkuICAgICAgICAgfAp8IEJVVCBXSEFUIEkgRE8gSEFWRSBJUyBBIFZFUlkgUEFSVElDVUxBUiBTRVQgT0YgU0tJTExTLCBTS0lMTFMgSSBIQVZFICAgICAgfAp8IEFDUVVJUkVEIE9WRVIgQSBWRVJZIExPTkcgQ0FSRUVSLCBTS0lMTFMgVEhBVCBNQUtFIE1FIEEgTklHSFRNQVJFIEZPUiAgICAgfAp8IFBFT1BMRSBMSUtFIFlPVS4gSUYgWU9VIExFVCBNWSBDT01QVVRFUiBTWVNURU0gR08gTk9XLCBUSEFUJ0xMIEJFIFRIRSAgICAgfAp8IEVORCBPRiBJVC4gSSBXSUxMIE5PVCBMT09LIEZPUiBZT1UsIEkgV0lMTCBOT1QgUFVSU1VFIFlPVS4gQlVUIElGIFlPVSAgICAgfAp8IERPTidULCBJIFdJTEwgTE9PSyBGT1IgWU9VLCBJIFdJTEwgRklORCBZT1UsIEFORCBJIFdJTEwgS0lMTCBZT1UuICAgICAgICAgfAp8X19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19ffAoKCg==
        mode: 0444
        filesystem: root
        overwrite: true
        path: /etc/motd
